apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wehrmacht-ingress
  labels:
    app: wehrmacht
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: w.34.29.127.41.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wehrmacht-service
            port:
              number: 8080
