apiVersion: v1
kind: Service
metadata:
  name: wehrmacht-service
  labels:
    app: wehrmacht
spec:
  type: ClusterIP
  selector:
    app: wehrmacht
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
