apiVersion: v1
kind: Service
metadata:
  name: wehrmacht-service
  labels:
    app: wehrmacht
spec:
  type: LoadBalancer
  selector:
    app: wehrmacht
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30700
    protocol: TCP
    name: http
